(define (problem RPG-1)
    (:domain RPG)
    (:requirements :strips :typing :negative-preconditions :conditional-effects :equality :universal-preconditions)
    (:objects 
        l1 l2 l3 l4 l5 - location
    )
    (:init
        (hp-next hp1 hp2)
        (hp-next hp2 hp3)
        (hp-next hp3 hp4)
        (player-at l1)
        (road l1 l2)
        (road l2 l3)
        (road l3 l4)
        (road l4 l5)
        (monster-at l3)
        (monster-hp l3 hp2)
        (monster-at l5)
        (monster-hp l5 hp1)
        (player-hp hp4)
    )
    (:goal
        (player-at l5)
    )
)
